### ISSUE TITLE
Trivial unsoundness with `nul_of_ref` macro.

### ISSUE THREAD

**Issue by rodrimati1992** [strake/null-terminated.rs#2]
The `nul_of_ref` macro as it's currently defined trivially allows for unsound code like this:
https://github.com/rodrimati1992/null-terminated.rs/blob/patch-1/examples/unsound.rs
```rust
extern crate null_terminated;
use null_terminated::{Nul,nul_of_ref};

static UNSOUND: &Nul<&std::convert::Infallible> = nul_of_ref![&0];

fn main(){
    dbg!(UNSOUND[0]);
}
```
Which is undefined behavior,that didn't require any unsafe code in the example.

Running the example currently outputs this:
```
[examples/unsound.rs:7] UNSOUND[0] = Illegal instruction (core dumped)
```

You can run the code with:
```
git clone https://github.com/rodrimati1992/null-terminated.rs.git
cd null-terminated.rs/
git checkout patch-1
cargo run --example unsound --release
```
<br><br><br><br>

Also,trying to run that example with my original code produces this compile time error:
```
error[E0308]: mismatched types
 --> examples/unsound.rs:4:63
  |
4 | static UNSOUND: &Nul<&std::convert::Infallible> = nul_of_ref![&0];
  |                                                               ^^ expected `!`, found integer
  |
  = note: expected reference `&!`
             found reference `&{integer}`
```

**Comment by strake** [comment]
Should be closed by https://github.com/strake/null-terminated.rs/commit/db3500869afda2e7400da41b8088e089a76698a9
